/**
 *
 *  PcPart.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace test
{

class PcPart
{
  public:
    struct Cols
    {
        static const std::string _ID;
        static const std::string _COSTCODE;
        static const std::string _PARTCODE;
        static const std::string _PARTNAME;
        static const std::string _STATUS;
        static const std::string _CREATEUSER;
        static const std::string _CREATEDATE;
        static const std::string _UPDATEUSER;
        static const std::string _UPDATEDATE;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = void;
    int getPrimaryKey() const { assert(false); return 0; }

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit PcPart(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit PcPart(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    PcPart(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    PcPart() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column ID  */
    ///Get the value of the column ID, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column ID
    void setId(const int32_t &pId) noexcept;

    /**  For column COSTCODE  */
    ///Get the value of the column COSTCODE, returns the default value if the column is null
    const std::string &getValueOfCostcode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCostcode() const noexcept;
    ///Set the value of the column COSTCODE
    void setCostcode(const std::string &pCostcode) noexcept;
    void setCostcode(std::string &&pCostcode) noexcept;
    void setCostcodeToNull() noexcept;

    /**  For column PARTCODE  */
    ///Get the value of the column PARTCODE, returns the default value if the column is null
    const std::string &getValueOfPartcode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPartcode() const noexcept;
    ///Set the value of the column PARTCODE
    void setPartcode(const std::string &pPartcode) noexcept;
    void setPartcode(std::string &&pPartcode) noexcept;
    void setPartcodeToNull() noexcept;

    /**  For column PARTNAME  */
    ///Get the value of the column PARTNAME, returns the default value if the column is null
    const std::string &getValueOfPartname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPartname() const noexcept;
    ///Set the value of the column PARTNAME
    void setPartname(const std::string &pPartname) noexcept;
    void setPartname(std::string &&pPartname) noexcept;
    void setPartnameToNull() noexcept;

    /**  For column STATUS  */
    ///Get the value of the column STATUS, returns the default value if the column is null
    const int32_t &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getStatus() const noexcept;
    ///Set the value of the column STATUS
    void setStatus(const int32_t &pStatus) noexcept;
    void setStatusToNull() noexcept;

    /**  For column CREATEUSER  */
    ///Get the value of the column CREATEUSER, returns the default value if the column is null
    const std::string &getValueOfCreateuser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreateuser() const noexcept;
    ///Set the value of the column CREATEUSER
    void setCreateuser(const std::string &pCreateuser) noexcept;
    void setCreateuser(std::string &&pCreateuser) noexcept;
    void setCreateuserToNull() noexcept;

    /**  For column CREATEDATE  */
    ///Get the value of the column CREATEDATE, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedate() const noexcept;
    ///Set the value of the column CREATEDATE
    void setCreatedate(const ::trantor::Date &pCreatedate) noexcept;
    void setCreatedateToNull() noexcept;

    /**  For column UPDATEUSER  */
    ///Get the value of the column UPDATEUSER, returns the default value if the column is null
    const std::string &getValueOfUpdateuser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUpdateuser() const noexcept;
    ///Set the value of the column UPDATEUSER
    void setUpdateuser(const std::string &pUpdateuser) noexcept;
    void setUpdateuser(std::string &&pUpdateuser) noexcept;
    void setUpdateuserToNull() noexcept;

    /**  For column UPDATEDATE  */
    ///Get the value of the column UPDATEDATE, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedate() const noexcept;
    ///Set the value of the column UPDATEDATE
    void setUpdatedate(const ::trantor::Date &pUpdatedate) noexcept;
    void setUpdatedateToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<PcPart>;
    friend drogon::orm::BaseBuilder<PcPart, true, true>;
    friend drogon::orm::BaseBuilder<PcPart, true, false>;
    friend drogon::orm::BaseBuilder<PcPart, false, true>;
    friend drogon::orm::BaseBuilder<PcPart, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<PcPart>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> costcode_;
    std::shared_ptr<std::string> partcode_;
    std::shared_ptr<std::string> partname_;
    std::shared_ptr<int32_t> status_;
    std::shared_ptr<std::string> createuser_;
    std::shared_ptr<::trantor::Date> createdate_;
    std::shared_ptr<std::string> updateuser_;
    std::shared_ptr<::trantor::Date> updatedate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "ID,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "COSTCODE,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "PARTCODE,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "PARTNAME,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "STATUS,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "CREATEUSER,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "CREATEDATE,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "UPDATEUSER,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "UPDATEDATE,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace test
} // namespace drogon_model
