/**
 *
 *  SisProDowntimeSetting.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "SisProDowntimeSetting.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::test;

const std::string SisProDowntimeSetting::Cols::_downtime_setting_id = "downtime_setting_id";
const std::string SisProDowntimeSetting::Cols::_code = "code";
const std::string SisProDowntimeSetting::Cols::_name = "name";
const std::string SisProDowntimeSetting::Cols::_month_of_record = "month_of_record";
const std::string SisProDowntimeSetting::Cols::_percent = "percent";
const std::string SisProDowntimeSetting::Cols::_dept_code = "dept_code";
const std::string SisProDowntimeSetting::Cols::_created_date = "created_date";
const std::string SisProDowntimeSetting::Cols::_created_by = "created_by";
const std::string SisProDowntimeSetting::Cols::_updated_date = "updated_date";
const std::string SisProDowntimeSetting::Cols::_updated_by = "updated_by";
const std::string SisProDowntimeSetting::Cols::_is_active = "is_active";
const std::string SisProDowntimeSetting::primaryKeyName = "";
const bool SisProDowntimeSetting::hasPrimaryKey = false;
const std::string SisProDowntimeSetting::tableName = "sis_pro_downtime_setting";

const std::vector<typename SisProDowntimeSetting::MetaData> SisProDowntimeSetting::metaData_={
{"downtime_setting_id","std::string","uuid",0,0,0,1},
{"code","std::string","character",0,0,0,0},
{"name","std::string","character varying",20,0,0,0},
{"month_of_record","std::string","character",0,0,0,0},
{"percent","std::string","numeric",0,0,0,0},
{"dept_code","std::string","character",0,0,0,0},
{"created_date","::trantor::Date","date",0,0,0,0},
{"created_by","std::string","character",0,0,0,0},
{"updated_date","::trantor::Date","timestamp with time zone",0,0,0,0},
{"updated_by","std::string","character",0,0,0,0},
{"is_active","bool","boolean",1,0,0,1}
};
const std::string &SisProDowntimeSetting::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
SisProDowntimeSetting::SisProDowntimeSetting(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["downtime_setting_id"].isNull())
        {
            downtimeSettingId_=std::make_shared<std::string>(r["downtime_setting_id"].as<std::string>());
        }
        if(!r["code"].isNull())
        {
            code_=std::make_shared<std::string>(r["code"].as<std::string>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["month_of_record"].isNull())
        {
            monthOfRecord_=std::make_shared<std::string>(r["month_of_record"].as<std::string>());
        }
        if(!r["percent"].isNull())
        {
            percent_=std::make_shared<std::string>(r["percent"].as<std::string>());
        }
        if(!r["dept_code"].isNull())
        {
            deptCode_=std::make_shared<std::string>(r["dept_code"].as<std::string>());
        }
        if(!r["created_date"].isNull())
        {
            auto daysStr = r["created_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            createdDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(r["created_by"].as<std::string>());
        }
        if(!r["updated_date"].isNull())
        {
            auto timeStr = r["updated_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(r["updated_by"].as<std::string>());
        }
        if(!r["is_active"].isNull())
        {
            isActive_=std::make_shared<bool>(r["is_active"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            downtimeSettingId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            code_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            monthOfRecord_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            percent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            deptCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            createdDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            updatedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            isActive_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

SisProDowntimeSetting::SisProDowntimeSetting(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            downtimeSettingId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            code_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            monthOfRecord_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            percent_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            deptCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            createdDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            isActive_=std::make_shared<bool>(pJson[pMasqueradingVector[10]].asBool());
        }
    }
}

SisProDowntimeSetting::SisProDowntimeSetting(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("downtime_setting_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["downtime_setting_id"].isNull())
        {
            downtimeSettingId_=std::make_shared<std::string>(pJson["downtime_setting_id"].asString());
        }
    }
    if(pJson.isMember("code"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["code"].isNull())
        {
            code_=std::make_shared<std::string>(pJson["code"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("month_of_record"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["month_of_record"].isNull())
        {
            monthOfRecord_=std::make_shared<std::string>(pJson["month_of_record"].asString());
        }
    }
    if(pJson.isMember("percent"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["percent"].isNull())
        {
            percent_=std::make_shared<std::string>(pJson["percent"].asString());
        }
    }
    if(pJson.isMember("dept_code"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["dept_code"].isNull())
        {
            deptCode_=std::make_shared<std::string>(pJson["dept_code"].asString());
        }
    }
    if(pJson.isMember("created_date"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_date"].isNull())
        {
            auto daysStr = pJson["created_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            createdDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson["created_by"].asString());
        }
    }
    if(pJson.isMember("updated_date"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["updated_date"].isNull())
        {
            auto timeStr = pJson["updated_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_by"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson["updated_by"].asString());
        }
    }
    if(pJson.isMember("is_active"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["is_active"].isNull())
        {
            isActive_=std::make_shared<bool>(pJson["is_active"].asBool());
        }
    }
}

void SisProDowntimeSetting::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            downtimeSettingId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            code_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            monthOfRecord_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            percent_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            deptCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            createdDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            isActive_=std::make_shared<bool>(pJson[pMasqueradingVector[10]].asBool());
        }
    }
}

void SisProDowntimeSetting::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("downtime_setting_id"))
    {
        dirtyFlag_[0] = true;
        if(!pJson["downtime_setting_id"].isNull())
        {
            downtimeSettingId_=std::make_shared<std::string>(pJson["downtime_setting_id"].asString());
        }
    }
    if(pJson.isMember("code"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["code"].isNull())
        {
            code_=std::make_shared<std::string>(pJson["code"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("month_of_record"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["month_of_record"].isNull())
        {
            monthOfRecord_=std::make_shared<std::string>(pJson["month_of_record"].asString());
        }
    }
    if(pJson.isMember("percent"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["percent"].isNull())
        {
            percent_=std::make_shared<std::string>(pJson["percent"].asString());
        }
    }
    if(pJson.isMember("dept_code"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["dept_code"].isNull())
        {
            deptCode_=std::make_shared<std::string>(pJson["dept_code"].asString());
        }
    }
    if(pJson.isMember("created_date"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_date"].isNull())
        {
            auto daysStr = pJson["created_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            createdDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson["created_by"].asString());
        }
    }
    if(pJson.isMember("updated_date"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["updated_date"].isNull())
        {
            auto timeStr = pJson["updated_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_by"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson["updated_by"].asString());
        }
    }
    if(pJson.isMember("is_active"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["is_active"].isNull())
        {
            isActive_=std::make_shared<bool>(pJson["is_active"].asBool());
        }
    }
}

const std::string &SisProDowntimeSetting::getValueOfDowntimeSettingId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(downtimeSettingId_)
        return *downtimeSettingId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getDowntimeSettingId() const noexcept
{
    return downtimeSettingId_;
}
void SisProDowntimeSetting::setDowntimeSettingId(const std::string &pDowntimeSettingId) noexcept
{
    downtimeSettingId_ = std::make_shared<std::string>(pDowntimeSettingId);
    dirtyFlag_[0] = true;
}
void SisProDowntimeSetting::setDowntimeSettingId(std::string &&pDowntimeSettingId) noexcept
{
    downtimeSettingId_ = std::make_shared<std::string>(std::move(pDowntimeSettingId));
    dirtyFlag_[0] = true;
}

const std::string &SisProDowntimeSetting::getValueOfCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(code_)
        return *code_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getCode() const noexcept
{
    return code_;
}
void SisProDowntimeSetting::setCode(const std::string &pCode) noexcept
{
    code_ = std::make_shared<std::string>(pCode);
    dirtyFlag_[1] = true;
}
void SisProDowntimeSetting::setCode(std::string &&pCode) noexcept
{
    code_ = std::make_shared<std::string>(std::move(pCode));
    dirtyFlag_[1] = true;
}
void SisProDowntimeSetting::setCodeToNull() noexcept
{
    code_.reset();
    dirtyFlag_[1] = true;
}

const std::string &SisProDowntimeSetting::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getName() const noexcept
{
    return name_;
}
void SisProDowntimeSetting::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[2] = true;
}
void SisProDowntimeSetting::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[2] = true;
}
void SisProDowntimeSetting::setNameToNull() noexcept
{
    name_.reset();
    dirtyFlag_[2] = true;
}

const std::string &SisProDowntimeSetting::getValueOfMonthOfRecord() const noexcept
{
    static const std::string defaultValue = std::string();
    if(monthOfRecord_)
        return *monthOfRecord_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getMonthOfRecord() const noexcept
{
    return monthOfRecord_;
}
void SisProDowntimeSetting::setMonthOfRecord(const std::string &pMonthOfRecord) noexcept
{
    monthOfRecord_ = std::make_shared<std::string>(pMonthOfRecord);
    dirtyFlag_[3] = true;
}
void SisProDowntimeSetting::setMonthOfRecord(std::string &&pMonthOfRecord) noexcept
{
    monthOfRecord_ = std::make_shared<std::string>(std::move(pMonthOfRecord));
    dirtyFlag_[3] = true;
}
void SisProDowntimeSetting::setMonthOfRecordToNull() noexcept
{
    monthOfRecord_.reset();
    dirtyFlag_[3] = true;
}

const std::string &SisProDowntimeSetting::getValueOfPercent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(percent_)
        return *percent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getPercent() const noexcept
{
    return percent_;
}
void SisProDowntimeSetting::setPercent(const std::string &pPercent) noexcept
{
    percent_ = std::make_shared<std::string>(pPercent);
    dirtyFlag_[4] = true;
}
void SisProDowntimeSetting::setPercent(std::string &&pPercent) noexcept
{
    percent_ = std::make_shared<std::string>(std::move(pPercent));
    dirtyFlag_[4] = true;
}
void SisProDowntimeSetting::setPercentToNull() noexcept
{
    percent_.reset();
    dirtyFlag_[4] = true;
}

const std::string &SisProDowntimeSetting::getValueOfDeptCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(deptCode_)
        return *deptCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getDeptCode() const noexcept
{
    return deptCode_;
}
void SisProDowntimeSetting::setDeptCode(const std::string &pDeptCode) noexcept
{
    deptCode_ = std::make_shared<std::string>(pDeptCode);
    dirtyFlag_[5] = true;
}
void SisProDowntimeSetting::setDeptCode(std::string &&pDeptCode) noexcept
{
    deptCode_ = std::make_shared<std::string>(std::move(pDeptCode));
    dirtyFlag_[5] = true;
}
void SisProDowntimeSetting::setDeptCodeToNull() noexcept
{
    deptCode_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &SisProDowntimeSetting::getValueOfCreatedDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdDate_)
        return *createdDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SisProDowntimeSetting::getCreatedDate() const noexcept
{
    return createdDate_;
}
void SisProDowntimeSetting::setCreatedDate(const ::trantor::Date &pCreatedDate) noexcept
{
    createdDate_ = std::make_shared<::trantor::Date>(pCreatedDate.roundDay());
    dirtyFlag_[6] = true;
}
void SisProDowntimeSetting::setCreatedDateToNull() noexcept
{
    createdDate_.reset();
    dirtyFlag_[6] = true;
}

const std::string &SisProDowntimeSetting::getValueOfCreatedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getCreatedBy() const noexcept
{
    return createdBy_;
}
void SisProDowntimeSetting::setCreatedBy(const std::string &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<std::string>(pCreatedBy);
    dirtyFlag_[7] = true;
}
void SisProDowntimeSetting::setCreatedBy(std::string &&pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<std::string>(std::move(pCreatedBy));
    dirtyFlag_[7] = true;
}
void SisProDowntimeSetting::setCreatedByToNull() noexcept
{
    createdBy_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &SisProDowntimeSetting::getValueOfUpdatedDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedDate_)
        return *updatedDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SisProDowntimeSetting::getUpdatedDate() const noexcept
{
    return updatedDate_;
}
void SisProDowntimeSetting::setUpdatedDate(const ::trantor::Date &pUpdatedDate) noexcept
{
    updatedDate_ = std::make_shared<::trantor::Date>(pUpdatedDate);
    dirtyFlag_[8] = true;
}
void SisProDowntimeSetting::setUpdatedDateToNull() noexcept
{
    updatedDate_.reset();
    dirtyFlag_[8] = true;
}

const std::string &SisProDowntimeSetting::getValueOfUpdatedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(updatedBy_)
        return *updatedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SisProDowntimeSetting::getUpdatedBy() const noexcept
{
    return updatedBy_;
}
void SisProDowntimeSetting::setUpdatedBy(const std::string &pUpdatedBy) noexcept
{
    updatedBy_ = std::make_shared<std::string>(pUpdatedBy);
    dirtyFlag_[9] = true;
}
void SisProDowntimeSetting::setUpdatedBy(std::string &&pUpdatedBy) noexcept
{
    updatedBy_ = std::make_shared<std::string>(std::move(pUpdatedBy));
    dirtyFlag_[9] = true;
}
void SisProDowntimeSetting::setUpdatedByToNull() noexcept
{
    updatedBy_.reset();
    dirtyFlag_[9] = true;
}

const bool &SisProDowntimeSetting::getValueOfIsActive() const noexcept
{
    static const bool defaultValue = bool();
    if(isActive_)
        return *isActive_;
    return defaultValue;
}
const std::shared_ptr<bool> &SisProDowntimeSetting::getIsActive() const noexcept
{
    return isActive_;
}
void SisProDowntimeSetting::setIsActive(const bool &pIsActive) noexcept
{
    isActive_ = std::make_shared<bool>(pIsActive);
    dirtyFlag_[10] = true;
}

void SisProDowntimeSetting::updateId(const uint64_t id)
{
}

const std::vector<std::string> &SisProDowntimeSetting::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "downtime_setting_id",
        "code",
        "name",
        "month_of_record",
        "percent",
        "dept_code",
        "created_date",
        "created_by",
        "updated_date",
        "updated_by",
        "is_active"
    };
    return inCols;
}

void SisProDowntimeSetting::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getDowntimeSettingId())
        {
            binder << getValueOfDowntimeSettingId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getCode())
        {
            binder << getValueOfCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMonthOfRecord())
        {
            binder << getValueOfMonthOfRecord();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPercent())
        {
            binder << getValueOfPercent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDeptCode())
        {
            binder << getValueOfDeptCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedDate())
        {
            binder << getValueOfCreatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUpdatedDate())
        {
            binder << getValueOfUpdatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUpdatedBy())
        {
            binder << getValueOfUpdatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getIsActive())
        {
            binder << getValueOfIsActive();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> SisProDowntimeSetting::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void SisProDowntimeSetting::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getDowntimeSettingId())
        {
            binder << getValueOfDowntimeSettingId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getCode())
        {
            binder << getValueOfCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMonthOfRecord())
        {
            binder << getValueOfMonthOfRecord();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPercent())
        {
            binder << getValueOfPercent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDeptCode())
        {
            binder << getValueOfDeptCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedDate())
        {
            binder << getValueOfCreatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUpdatedDate())
        {
            binder << getValueOfUpdatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUpdatedBy())
        {
            binder << getValueOfUpdatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getIsActive())
        {
            binder << getValueOfIsActive();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value SisProDowntimeSetting::toJson() const
{
    Json::Value ret;
    if(getDowntimeSettingId())
    {
        ret["downtime_setting_id"]=getValueOfDowntimeSettingId();
    }
    else
    {
        ret["downtime_setting_id"]=Json::Value();
    }
    if(getCode())
    {
        ret["code"]=getValueOfCode();
    }
    else
    {
        ret["code"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getMonthOfRecord())
    {
        ret["month_of_record"]=getValueOfMonthOfRecord();
    }
    else
    {
        ret["month_of_record"]=Json::Value();
    }
    if(getPercent())
    {
        ret["percent"]=getValueOfPercent();
    }
    else
    {
        ret["percent"]=Json::Value();
    }
    if(getDeptCode())
    {
        ret["dept_code"]=getValueOfDeptCode();
    }
    else
    {
        ret["dept_code"]=Json::Value();
    }
    if(getCreatedDate())
    {
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    }
    else
    {
        ret["created_date"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getUpdatedDate())
    {
        ret["updated_date"]=getUpdatedDate()->toDbStringLocal();
    }
    else
    {
        ret["updated_date"]=Json::Value();
    }
    if(getUpdatedBy())
    {
        ret["updated_by"]=getValueOfUpdatedBy();
    }
    else
    {
        ret["updated_by"]=Json::Value();
    }
    if(getIsActive())
    {
        ret["is_active"]=getValueOfIsActive();
    }
    else
    {
        ret["is_active"]=Json::Value();
    }
    return ret;
}

Json::Value SisProDowntimeSetting::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getDowntimeSettingId())
            {
                ret[pMasqueradingVector[0]]=getValueOfDowntimeSettingId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getCode())
            {
                ret[pMasqueradingVector[1]]=getValueOfCode();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[2]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMonthOfRecord())
            {
                ret[pMasqueradingVector[3]]=getValueOfMonthOfRecord();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPercent())
            {
                ret[pMasqueradingVector[4]]=getValueOfPercent();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDeptCode())
            {
                ret[pMasqueradingVector[5]]=getValueOfDeptCode();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedDate())
            {
                ret[pMasqueradingVector[6]]=getCreatedDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[7]]=getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getUpdatedDate())
            {
                ret[pMasqueradingVector[8]]=getUpdatedDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getUpdatedBy())
            {
                ret[pMasqueradingVector[9]]=getValueOfUpdatedBy();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getIsActive())
            {
                ret[pMasqueradingVector[10]]=getValueOfIsActive();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getDowntimeSettingId())
    {
        ret["downtime_setting_id"]=getValueOfDowntimeSettingId();
    }
    else
    {
        ret["downtime_setting_id"]=Json::Value();
    }
    if(getCode())
    {
        ret["code"]=getValueOfCode();
    }
    else
    {
        ret["code"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getMonthOfRecord())
    {
        ret["month_of_record"]=getValueOfMonthOfRecord();
    }
    else
    {
        ret["month_of_record"]=Json::Value();
    }
    if(getPercent())
    {
        ret["percent"]=getValueOfPercent();
    }
    else
    {
        ret["percent"]=Json::Value();
    }
    if(getDeptCode())
    {
        ret["dept_code"]=getValueOfDeptCode();
    }
    else
    {
        ret["dept_code"]=Json::Value();
    }
    if(getCreatedDate())
    {
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    }
    else
    {
        ret["created_date"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getUpdatedDate())
    {
        ret["updated_date"]=getUpdatedDate()->toDbStringLocal();
    }
    else
    {
        ret["updated_date"]=Json::Value();
    }
    if(getUpdatedBy())
    {
        ret["updated_by"]=getValueOfUpdatedBy();
    }
    else
    {
        ret["updated_by"]=Json::Value();
    }
    if(getIsActive())
    {
        ret["is_active"]=getValueOfIsActive();
    }
    else
    {
        ret["is_active"]=Json::Value();
    }
    return ret;
}

bool SisProDowntimeSetting::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("downtime_setting_id"))
    {
        if(!validJsonOfField(0, "downtime_setting_id", pJson["downtime_setting_id"], err, true))
            return false;
    }
    else
    {
        err="The downtime_setting_id column cannot be null";
        return false;
    }
    if(pJson.isMember("code"))
    {
        if(!validJsonOfField(1, "code", pJson["code"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, true))
            return false;
    }
    if(pJson.isMember("month_of_record"))
    {
        if(!validJsonOfField(3, "month_of_record", pJson["month_of_record"], err, true))
            return false;
    }
    if(pJson.isMember("percent"))
    {
        if(!validJsonOfField(4, "percent", pJson["percent"], err, true))
            return false;
    }
    if(pJson.isMember("dept_code"))
    {
        if(!validJsonOfField(5, "dept_code", pJson["dept_code"], err, true))
            return false;
    }
    if(pJson.isMember("created_date"))
    {
        if(!validJsonOfField(6, "created_date", pJson["created_date"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(7, "created_by", pJson["created_by"], err, true))
            return false;
    }
    if(pJson.isMember("updated_date"))
    {
        if(!validJsonOfField(8, "updated_date", pJson["updated_date"], err, true))
            return false;
    }
    if(pJson.isMember("updated_by"))
    {
        if(!validJsonOfField(9, "updated_by", pJson["updated_by"], err, true))
            return false;
    }
    if(pJson.isMember("is_active"))
    {
        if(!validJsonOfField(10, "is_active", pJson["is_active"], err, true))
            return false;
    }
    else
    {
        err="The is_active column cannot be null";
        return false;
    }
    return true;
}
bool SisProDowntimeSetting::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                               const std::vector<std::string> &pMasqueradingVector,
                                                               std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[10] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SisProDowntimeSetting::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("downtime_setting_id"))
    {
        if(!validJsonOfField(0, "downtime_setting_id", pJson["downtime_setting_id"], err, false))
            return false;
    }
    if(pJson.isMember("code"))
    {
        if(!validJsonOfField(1, "code", pJson["code"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("month_of_record"))
    {
        if(!validJsonOfField(3, "month_of_record", pJson["month_of_record"], err, false))
            return false;
    }
    if(pJson.isMember("percent"))
    {
        if(!validJsonOfField(4, "percent", pJson["percent"], err, false))
            return false;
    }
    if(pJson.isMember("dept_code"))
    {
        if(!validJsonOfField(5, "dept_code", pJson["dept_code"], err, false))
            return false;
    }
    if(pJson.isMember("created_date"))
    {
        if(!validJsonOfField(6, "created_date", pJson["created_date"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(7, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("updated_date"))
    {
        if(!validJsonOfField(8, "updated_date", pJson["updated_date"], err, false))
            return false;
    }
    if(pJson.isMember("updated_by"))
    {
        if(!validJsonOfField(9, "updated_by", pJson["updated_by"], err, false))
            return false;
    }
    if(pJson.isMember("is_active"))
    {
        if(!validJsonOfField(10, "is_active", pJson["is_active"], err, false))
            return false;
    }
    return true;
}
bool SisProDowntimeSetting::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SisProDowntimeSetting::validJsonOfField(size_t index,
                                             const std::string &fieldName,
                                             const Json::Value &pJson,
                                             std::string &err,
                                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
