/**
 *
 *  SystemSerialDetail.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace smart
{

class SystemSerialDetail
{
  public:
    struct Cols
    {
        static const std::string _code;
        static const std::string _LineNo;
        static const std::string _start_date;
        static const std::string _start_serial_no;
        static const std::string _prefix;
        static const std::string _suffix;
        static const std::string _step;
        static const std::string _last_serial_no;
        static const std::string _last_used_date;
        static const std::string _created_date;
        static const std::string _created_by;
        static const std::string _updated_date;
        static const std::string _updated_by;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = void;
    int getPrimaryKey() const { assert(false); return 0; }

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit SystemSerialDetail(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit SystemSerialDetail(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    SystemSerialDetail(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    SystemSerialDetail() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column code  */
    ///Get the value of the column code, returns the default value if the column is null
    const std::string &getValueOfCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCode() const noexcept;
    ///Set the value of the column code
    void setCode(const std::string &pCode) noexcept;
    void setCode(std::string &&pCode) noexcept;
    void setCodeToNull() noexcept;

    /**  For column LineNo  */
    ///Get the value of the column LineNo, returns the default value if the column is null
    const int32_t &getValueOfLineno() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getLineno() const noexcept;
    ///Set the value of the column LineNo
    void setLineno(const int32_t &pLineno) noexcept;

    /**  For column start_date  */
    ///Get the value of the column start_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfStartDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getStartDate() const noexcept;
    ///Set the value of the column start_date
    void setStartDate(const ::trantor::Date &pStartDate) noexcept;
    void setStartDateToNull() noexcept;

    /**  For column start_serial_no  */
    ///Get the value of the column start_serial_no, returns the default value if the column is null
    const std::string &getValueOfStartSerialNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStartSerialNo() const noexcept;
    ///Set the value of the column start_serial_no
    void setStartSerialNo(const std::string &pStartSerialNo) noexcept;
    void setStartSerialNo(std::string &&pStartSerialNo) noexcept;
    void setStartSerialNoToNull() noexcept;

    /**  For column prefix  */
    ///Get the value of the column prefix, returns the default value if the column is null
    const std::string &getValueOfPrefix() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPrefix() const noexcept;
    ///Set the value of the column prefix
    void setPrefix(const std::string &pPrefix) noexcept;
    void setPrefix(std::string &&pPrefix) noexcept;
    void setPrefixToNull() noexcept;

    /**  For column suffix  */
    ///Get the value of the column suffix, returns the default value if the column is null
    const std::string &getValueOfSuffix() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSuffix() const noexcept;
    ///Set the value of the column suffix
    void setSuffix(const std::string &pSuffix) noexcept;
    void setSuffix(std::string &&pSuffix) noexcept;
    void setSuffixToNull() noexcept;

    /**  For column step  */
    ///Get the value of the column step, returns the default value if the column is null
    const int32_t &getValueOfStep() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getStep() const noexcept;
    ///Set the value of the column step
    void setStep(const int32_t &pStep) noexcept;
    void setStepToNull() noexcept;

    /**  For column last_serial_no  */
    ///Get the value of the column last_serial_no, returns the default value if the column is null
    const std::string &getValueOfLastSerialNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLastSerialNo() const noexcept;
    ///Set the value of the column last_serial_no
    void setLastSerialNo(const std::string &pLastSerialNo) noexcept;
    void setLastSerialNo(std::string &&pLastSerialNo) noexcept;
    void setLastSerialNoToNull() noexcept;

    /**  For column last_used_date  */
    ///Get the value of the column last_used_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastUsedDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastUsedDate() const noexcept;
    ///Set the value of the column last_used_date
    void setLastUsedDate(const ::trantor::Date &pLastUsedDate) noexcept;
    void setLastUsedDateToNull() noexcept;

    /**  For column created_date  */
    ///Get the value of the column created_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedDate() const noexcept;
    ///Set the value of the column created_date
    void setCreatedDate(const ::trantor::Date &pCreatedDate) noexcept;
    void setCreatedDateToNull() noexcept;

    /**  For column created_by  */
    ///Get the value of the column created_by, returns the default value if the column is null
    const std::string &getValueOfCreatedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCreatedBy() const noexcept;
    ///Set the value of the column created_by
    void setCreatedBy(const std::string &pCreatedBy) noexcept;
    void setCreatedBy(std::string &&pCreatedBy) noexcept;
    void setCreatedByToNull() noexcept;

    /**  For column updated_date  */
    ///Get the value of the column updated_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedDate() const noexcept;
    ///Set the value of the column updated_date
    void setUpdatedDate(const ::trantor::Date &pUpdatedDate) noexcept;
    void setUpdatedDateToNull() noexcept;

    /**  For column updated_by  */
    ///Get the value of the column updated_by, returns the default value if the column is null
    const std::string &getValueOfUpdatedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUpdatedBy() const noexcept;
    ///Set the value of the column updated_by
    void setUpdatedBy(const std::string &pUpdatedBy) noexcept;
    void setUpdatedBy(std::string &&pUpdatedBy) noexcept;
    void setUpdatedByToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<SystemSerialDetail>;
    friend drogon::orm::BaseBuilder<SystemSerialDetail, true, true>;
    friend drogon::orm::BaseBuilder<SystemSerialDetail, true, false>;
    friend drogon::orm::BaseBuilder<SystemSerialDetail, false, true>;
    friend drogon::orm::BaseBuilder<SystemSerialDetail, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<SystemSerialDetail>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> code_;
    std::shared_ptr<int32_t> lineno_;
    std::shared_ptr<::trantor::Date> startDate_;
    std::shared_ptr<std::string> startSerialNo_;
    std::shared_ptr<std::string> prefix_;
    std::shared_ptr<std::string> suffix_;
    std::shared_ptr<int32_t> step_;
    std::shared_ptr<std::string> lastSerialNo_;
    std::shared_ptr<::trantor::Date> lastUsedDate_;
    std::shared_ptr<::trantor::Date> createdDate_;
    std::shared_ptr<std::string> createdBy_;
    std::shared_ptr<::trantor::Date> updatedDate_;
    std::shared_ptr<std::string> updatedBy_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "code,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "LineNo,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "start_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "start_serial_no,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "prefix,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "suffix,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "step,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "last_serial_no,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "last_used_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "created_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "created_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "updated_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "updated_by,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace smart
} // namespace drogon_model
