/**
 *
 *  SystemSerialDetail.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "SystemSerialDetail.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::smart;

const std::string SystemSerialDetail::Cols::_code = "code";
const std::string SystemSerialDetail::Cols::_LineNo = "LineNo";
const std::string SystemSerialDetail::Cols::_start_date = "start_date";
const std::string SystemSerialDetail::Cols::_start_serial_no = "start_serial_no";
const std::string SystemSerialDetail::Cols::_prefix = "prefix";
const std::string SystemSerialDetail::Cols::_suffix = "suffix";
const std::string SystemSerialDetail::Cols::_step = "step";
const std::string SystemSerialDetail::Cols::_last_serial_no = "last_serial_no";
const std::string SystemSerialDetail::Cols::_last_used_date = "last_used_date";
const std::string SystemSerialDetail::Cols::_created_date = "created_date";
const std::string SystemSerialDetail::Cols::_created_by = "created_by";
const std::string SystemSerialDetail::Cols::_updated_date = "updated_date";
const std::string SystemSerialDetail::Cols::_updated_by = "updated_by";
const std::string SystemSerialDetail::primaryKeyName = "";
const bool SystemSerialDetail::hasPrimaryKey = false;
const std::string SystemSerialDetail::tableName = "system_serial_detail";

const std::vector<typename SystemSerialDetail::MetaData> SystemSerialDetail::metaData_={
{"code","std::string","character varying",20,0,0,0},
{"LineNo","int32_t","integer",4,0,0,1},
{"start_date","::trantor::Date","date",0,0,0,0},
{"start_serial_no","std::string","character varying",30,0,0,0},
{"prefix","std::string","character varying",30,0,0,0},
{"suffix","std::string","character varying",30,0,0,0},
{"step","int32_t","integer",4,0,0,0},
{"last_serial_no","std::string","character varying",30,0,0,0},
{"last_used_date","::trantor::Date","date",0,0,0,0},
{"created_date","::trantor::Date","timestamp without time zone",0,0,0,0},
{"created_by","std::string","character varying",10,0,0,0},
{"updated_date","::trantor::Date","timestamp without time zone",0,0,0,0},
{"updated_by","std::string","character varying",10,0,0,0}
};
const std::string &SystemSerialDetail::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
SystemSerialDetail::SystemSerialDetail(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["code"].isNull())
        {
            code_=std::make_shared<std::string>(r["code"].as<std::string>());
        }
        if(!r["LineNo"].isNull())
        {
            lineno_=std::make_shared<int32_t>(r["LineNo"].as<int32_t>());
        }
        if(!r["start_date"].isNull())
        {
            auto daysStr = r["start_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["start_serial_no"].isNull())
        {
            startSerialNo_=std::make_shared<std::string>(r["start_serial_no"].as<std::string>());
        }
        if(!r["prefix"].isNull())
        {
            prefix_=std::make_shared<std::string>(r["prefix"].as<std::string>());
        }
        if(!r["suffix"].isNull())
        {
            suffix_=std::make_shared<std::string>(r["suffix"].as<std::string>());
        }
        if(!r["step"].isNull())
        {
            step_=std::make_shared<int32_t>(r["step"].as<int32_t>());
        }
        if(!r["last_serial_no"].isNull())
        {
            lastSerialNo_=std::make_shared<std::string>(r["last_serial_no"].as<std::string>());
        }
        if(!r["last_used_date"].isNull())
        {
            auto daysStr = r["last_used_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            lastUsedDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["created_date"].isNull())
        {
            auto timeStr = r["created_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(r["created_by"].as<std::string>());
        }
        if(!r["updated_date"].isNull())
        {
            auto timeStr = r["updated_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(r["updated_by"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            code_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            lineno_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            startSerialNo_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            prefix_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            suffix_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            step_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            lastSerialNo_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            lastUsedDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            updatedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

SystemSerialDetail::SystemSerialDetail(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            code_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            lineno_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            startSerialNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            prefix_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            suffix_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            step_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            lastSerialNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            lastUsedDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
}

SystemSerialDetail::SystemSerialDetail(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("code"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["code"].isNull())
        {
            code_=std::make_shared<std::string>(pJson["code"].asString());
        }
    }
    if(pJson.isMember("LineNo"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["LineNo"].isNull())
        {
            lineno_=std::make_shared<int32_t>((int32_t)pJson["LineNo"].asInt64());
        }
    }
    if(pJson.isMember("start_date"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["start_date"].isNull())
        {
            auto daysStr = pJson["start_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("start_serial_no"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["start_serial_no"].isNull())
        {
            startSerialNo_=std::make_shared<std::string>(pJson["start_serial_no"].asString());
        }
    }
    if(pJson.isMember("prefix"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["prefix"].isNull())
        {
            prefix_=std::make_shared<std::string>(pJson["prefix"].asString());
        }
    }
    if(pJson.isMember("suffix"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["suffix"].isNull())
        {
            suffix_=std::make_shared<std::string>(pJson["suffix"].asString());
        }
    }
    if(pJson.isMember("step"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["step"].isNull())
        {
            step_=std::make_shared<int32_t>((int32_t)pJson["step"].asInt64());
        }
    }
    if(pJson.isMember("last_serial_no"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["last_serial_no"].isNull())
        {
            lastSerialNo_=std::make_shared<std::string>(pJson["last_serial_no"].asString());
        }
    }
    if(pJson.isMember("last_used_date"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["last_used_date"].isNull())
        {
            auto daysStr = pJson["last_used_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            lastUsedDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("created_date"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["created_date"].isNull())
        {
            auto timeStr = pJson["created_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson["created_by"].asString());
        }
    }
    if(pJson.isMember("updated_date"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["updated_date"].isNull())
        {
            auto timeStr = pJson["updated_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_by"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson["updated_by"].asString());
        }
    }
}

void SystemSerialDetail::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            code_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            lineno_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            startSerialNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            prefix_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            suffix_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            step_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            lastSerialNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            lastUsedDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
}

void SystemSerialDetail::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("code"))
    {
        dirtyFlag_[0] = true;
        if(!pJson["code"].isNull())
        {
            code_=std::make_shared<std::string>(pJson["code"].asString());
        }
    }
    if(pJson.isMember("LineNo"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["LineNo"].isNull())
        {
            lineno_=std::make_shared<int32_t>((int32_t)pJson["LineNo"].asInt64());
        }
    }
    if(pJson.isMember("start_date"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["start_date"].isNull())
        {
            auto daysStr = pJson["start_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("start_serial_no"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["start_serial_no"].isNull())
        {
            startSerialNo_=std::make_shared<std::string>(pJson["start_serial_no"].asString());
        }
    }
    if(pJson.isMember("prefix"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["prefix"].isNull())
        {
            prefix_=std::make_shared<std::string>(pJson["prefix"].asString());
        }
    }
    if(pJson.isMember("suffix"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["suffix"].isNull())
        {
            suffix_=std::make_shared<std::string>(pJson["suffix"].asString());
        }
    }
    if(pJson.isMember("step"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["step"].isNull())
        {
            step_=std::make_shared<int32_t>((int32_t)pJson["step"].asInt64());
        }
    }
    if(pJson.isMember("last_serial_no"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["last_serial_no"].isNull())
        {
            lastSerialNo_=std::make_shared<std::string>(pJson["last_serial_no"].asString());
        }
    }
    if(pJson.isMember("last_used_date"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["last_used_date"].isNull())
        {
            auto daysStr = pJson["last_used_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            lastUsedDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("created_date"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["created_date"].isNull())
        {
            auto timeStr = pJson["created_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<std::string>(pJson["created_by"].asString());
        }
    }
    if(pJson.isMember("updated_date"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["updated_date"].isNull())
        {
            auto timeStr = pJson["updated_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_by"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson["updated_by"].asString());
        }
    }
}

const std::string &SystemSerialDetail::getValueOfCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(code_)
        return *code_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getCode() const noexcept
{
    return code_;
}
void SystemSerialDetail::setCode(const std::string &pCode) noexcept
{
    code_ = std::make_shared<std::string>(pCode);
    dirtyFlag_[0] = true;
}
void SystemSerialDetail::setCode(std::string &&pCode) noexcept
{
    code_ = std::make_shared<std::string>(std::move(pCode));
    dirtyFlag_[0] = true;
}
void SystemSerialDetail::setCodeToNull() noexcept
{
    code_.reset();
    dirtyFlag_[0] = true;
}

const int32_t &SystemSerialDetail::getValueOfLineno() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(lineno_)
        return *lineno_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &SystemSerialDetail::getLineno() const noexcept
{
    return lineno_;
}
void SystemSerialDetail::setLineno(const int32_t &pLineno) noexcept
{
    lineno_ = std::make_shared<int32_t>(pLineno);
    dirtyFlag_[1] = true;
}

const ::trantor::Date &SystemSerialDetail::getValueOfStartDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(startDate_)
        return *startDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SystemSerialDetail::getStartDate() const noexcept
{
    return startDate_;
}
void SystemSerialDetail::setStartDate(const ::trantor::Date &pStartDate) noexcept
{
    startDate_ = std::make_shared<::trantor::Date>(pStartDate.roundDay());
    dirtyFlag_[2] = true;
}
void SystemSerialDetail::setStartDateToNull() noexcept
{
    startDate_.reset();
    dirtyFlag_[2] = true;
}

const std::string &SystemSerialDetail::getValueOfStartSerialNo() const noexcept
{
    static const std::string defaultValue = std::string();
    if(startSerialNo_)
        return *startSerialNo_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getStartSerialNo() const noexcept
{
    return startSerialNo_;
}
void SystemSerialDetail::setStartSerialNo(const std::string &pStartSerialNo) noexcept
{
    startSerialNo_ = std::make_shared<std::string>(pStartSerialNo);
    dirtyFlag_[3] = true;
}
void SystemSerialDetail::setStartSerialNo(std::string &&pStartSerialNo) noexcept
{
    startSerialNo_ = std::make_shared<std::string>(std::move(pStartSerialNo));
    dirtyFlag_[3] = true;
}
void SystemSerialDetail::setStartSerialNoToNull() noexcept
{
    startSerialNo_.reset();
    dirtyFlag_[3] = true;
}

const std::string &SystemSerialDetail::getValueOfPrefix() const noexcept
{
    static const std::string defaultValue = std::string();
    if(prefix_)
        return *prefix_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getPrefix() const noexcept
{
    return prefix_;
}
void SystemSerialDetail::setPrefix(const std::string &pPrefix) noexcept
{
    prefix_ = std::make_shared<std::string>(pPrefix);
    dirtyFlag_[4] = true;
}
void SystemSerialDetail::setPrefix(std::string &&pPrefix) noexcept
{
    prefix_ = std::make_shared<std::string>(std::move(pPrefix));
    dirtyFlag_[4] = true;
}
void SystemSerialDetail::setPrefixToNull() noexcept
{
    prefix_.reset();
    dirtyFlag_[4] = true;
}

const std::string &SystemSerialDetail::getValueOfSuffix() const noexcept
{
    static const std::string defaultValue = std::string();
    if(suffix_)
        return *suffix_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getSuffix() const noexcept
{
    return suffix_;
}
void SystemSerialDetail::setSuffix(const std::string &pSuffix) noexcept
{
    suffix_ = std::make_shared<std::string>(pSuffix);
    dirtyFlag_[5] = true;
}
void SystemSerialDetail::setSuffix(std::string &&pSuffix) noexcept
{
    suffix_ = std::make_shared<std::string>(std::move(pSuffix));
    dirtyFlag_[5] = true;
}
void SystemSerialDetail::setSuffixToNull() noexcept
{
    suffix_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &SystemSerialDetail::getValueOfStep() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(step_)
        return *step_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &SystemSerialDetail::getStep() const noexcept
{
    return step_;
}
void SystemSerialDetail::setStep(const int32_t &pStep) noexcept
{
    step_ = std::make_shared<int32_t>(pStep);
    dirtyFlag_[6] = true;
}
void SystemSerialDetail::setStepToNull() noexcept
{
    step_.reset();
    dirtyFlag_[6] = true;
}

const std::string &SystemSerialDetail::getValueOfLastSerialNo() const noexcept
{
    static const std::string defaultValue = std::string();
    if(lastSerialNo_)
        return *lastSerialNo_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getLastSerialNo() const noexcept
{
    return lastSerialNo_;
}
void SystemSerialDetail::setLastSerialNo(const std::string &pLastSerialNo) noexcept
{
    lastSerialNo_ = std::make_shared<std::string>(pLastSerialNo);
    dirtyFlag_[7] = true;
}
void SystemSerialDetail::setLastSerialNo(std::string &&pLastSerialNo) noexcept
{
    lastSerialNo_ = std::make_shared<std::string>(std::move(pLastSerialNo));
    dirtyFlag_[7] = true;
}
void SystemSerialDetail::setLastSerialNoToNull() noexcept
{
    lastSerialNo_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &SystemSerialDetail::getValueOfLastUsedDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastUsedDate_)
        return *lastUsedDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SystemSerialDetail::getLastUsedDate() const noexcept
{
    return lastUsedDate_;
}
void SystemSerialDetail::setLastUsedDate(const ::trantor::Date &pLastUsedDate) noexcept
{
    lastUsedDate_ = std::make_shared<::trantor::Date>(pLastUsedDate.roundDay());
    dirtyFlag_[8] = true;
}
void SystemSerialDetail::setLastUsedDateToNull() noexcept
{
    lastUsedDate_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &SystemSerialDetail::getValueOfCreatedDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdDate_)
        return *createdDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SystemSerialDetail::getCreatedDate() const noexcept
{
    return createdDate_;
}
void SystemSerialDetail::setCreatedDate(const ::trantor::Date &pCreatedDate) noexcept
{
    createdDate_ = std::make_shared<::trantor::Date>(pCreatedDate);
    dirtyFlag_[9] = true;
}
void SystemSerialDetail::setCreatedDateToNull() noexcept
{
    createdDate_.reset();
    dirtyFlag_[9] = true;
}

const std::string &SystemSerialDetail::getValueOfCreatedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getCreatedBy() const noexcept
{
    return createdBy_;
}
void SystemSerialDetail::setCreatedBy(const std::string &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<std::string>(pCreatedBy);
    dirtyFlag_[10] = true;
}
void SystemSerialDetail::setCreatedBy(std::string &&pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<std::string>(std::move(pCreatedBy));
    dirtyFlag_[10] = true;
}
void SystemSerialDetail::setCreatedByToNull() noexcept
{
    createdBy_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &SystemSerialDetail::getValueOfUpdatedDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedDate_)
        return *updatedDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SystemSerialDetail::getUpdatedDate() const noexcept
{
    return updatedDate_;
}
void SystemSerialDetail::setUpdatedDate(const ::trantor::Date &pUpdatedDate) noexcept
{
    updatedDate_ = std::make_shared<::trantor::Date>(pUpdatedDate);
    dirtyFlag_[11] = true;
}
void SystemSerialDetail::setUpdatedDateToNull() noexcept
{
    updatedDate_.reset();
    dirtyFlag_[11] = true;
}

const std::string &SystemSerialDetail::getValueOfUpdatedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(updatedBy_)
        return *updatedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SystemSerialDetail::getUpdatedBy() const noexcept
{
    return updatedBy_;
}
void SystemSerialDetail::setUpdatedBy(const std::string &pUpdatedBy) noexcept
{
    updatedBy_ = std::make_shared<std::string>(pUpdatedBy);
    dirtyFlag_[12] = true;
}
void SystemSerialDetail::setUpdatedBy(std::string &&pUpdatedBy) noexcept
{
    updatedBy_ = std::make_shared<std::string>(std::move(pUpdatedBy));
    dirtyFlag_[12] = true;
}
void SystemSerialDetail::setUpdatedByToNull() noexcept
{
    updatedBy_.reset();
    dirtyFlag_[12] = true;
}

void SystemSerialDetail::updateId(const uint64_t id)
{
}

const std::vector<std::string> &SystemSerialDetail::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "code",
        "LineNo",
        "start_date",
        "start_serial_no",
        "prefix",
        "suffix",
        "step",
        "last_serial_no",
        "last_used_date",
        "created_date",
        "created_by",
        "updated_date",
        "updated_by"
    };
    return inCols;
}

void SystemSerialDetail::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCode())
        {
            binder << getValueOfCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getLineno())
        {
            binder << getValueOfLineno();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStartDate())
        {
            binder << getValueOfStartDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStartSerialNo())
        {
            binder << getValueOfStartSerialNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrefix())
        {
            binder << getValueOfPrefix();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSuffix())
        {
            binder << getValueOfSuffix();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStep())
        {
            binder << getValueOfStep();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastSerialNo())
        {
            binder << getValueOfLastSerialNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLastUsedDate())
        {
            binder << getValueOfLastUsedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedDate())
        {
            binder << getValueOfCreatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getUpdatedDate())
        {
            binder << getValueOfUpdatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedBy())
        {
            binder << getValueOfUpdatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> SystemSerialDetail::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void SystemSerialDetail::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCode())
        {
            binder << getValueOfCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getLineno())
        {
            binder << getValueOfLineno();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStartDate())
        {
            binder << getValueOfStartDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStartSerialNo())
        {
            binder << getValueOfStartSerialNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrefix())
        {
            binder << getValueOfPrefix();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSuffix())
        {
            binder << getValueOfSuffix();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStep())
        {
            binder << getValueOfStep();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastSerialNo())
        {
            binder << getValueOfLastSerialNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLastUsedDate())
        {
            binder << getValueOfLastUsedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedDate())
        {
            binder << getValueOfCreatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getUpdatedDate())
        {
            binder << getValueOfUpdatedDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedBy())
        {
            binder << getValueOfUpdatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value SystemSerialDetail::toJson() const
{
    Json::Value ret;
    if(getCode())
    {
        ret["code"]=getValueOfCode();
    }
    else
    {
        ret["code"]=Json::Value();
    }
    if(getLineno())
    {
        ret["LineNo"]=getValueOfLineno();
    }
    else
    {
        ret["LineNo"]=Json::Value();
    }
    if(getStartDate())
    {
        ret["start_date"]=getStartDate()->toDbStringLocal();
    }
    else
    {
        ret["start_date"]=Json::Value();
    }
    if(getStartSerialNo())
    {
        ret["start_serial_no"]=getValueOfStartSerialNo();
    }
    else
    {
        ret["start_serial_no"]=Json::Value();
    }
    if(getPrefix())
    {
        ret["prefix"]=getValueOfPrefix();
    }
    else
    {
        ret["prefix"]=Json::Value();
    }
    if(getSuffix())
    {
        ret["suffix"]=getValueOfSuffix();
    }
    else
    {
        ret["suffix"]=Json::Value();
    }
    if(getStep())
    {
        ret["step"]=getValueOfStep();
    }
    else
    {
        ret["step"]=Json::Value();
    }
    if(getLastSerialNo())
    {
        ret["last_serial_no"]=getValueOfLastSerialNo();
    }
    else
    {
        ret["last_serial_no"]=Json::Value();
    }
    if(getLastUsedDate())
    {
        ret["last_used_date"]=getLastUsedDate()->toDbStringLocal();
    }
    else
    {
        ret["last_used_date"]=Json::Value();
    }
    if(getCreatedDate())
    {
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    }
    else
    {
        ret["created_date"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getUpdatedDate())
    {
        ret["updated_date"]=getUpdatedDate()->toDbStringLocal();
    }
    else
    {
        ret["updated_date"]=Json::Value();
    }
    if(getUpdatedBy())
    {
        ret["updated_by"]=getValueOfUpdatedBy();
    }
    else
    {
        ret["updated_by"]=Json::Value();
    }
    return ret;
}

Json::Value SystemSerialDetail::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCode())
            {
                ret[pMasqueradingVector[0]]=getValueOfCode();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getLineno())
            {
                ret[pMasqueradingVector[1]]=getValueOfLineno();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getStartDate())
            {
                ret[pMasqueradingVector[2]]=getStartDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getStartSerialNo())
            {
                ret[pMasqueradingVector[3]]=getValueOfStartSerialNo();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPrefix())
            {
                ret[pMasqueradingVector[4]]=getValueOfPrefix();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getSuffix())
            {
                ret[pMasqueradingVector[5]]=getValueOfSuffix();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStep())
            {
                ret[pMasqueradingVector[6]]=getValueOfStep();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getLastSerialNo())
            {
                ret[pMasqueradingVector[7]]=getValueOfLastSerialNo();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getLastUsedDate())
            {
                ret[pMasqueradingVector[8]]=getLastUsedDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCreatedDate())
            {
                ret[pMasqueradingVector[9]]=getCreatedDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[10]]=getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getUpdatedDate())
            {
                ret[pMasqueradingVector[11]]=getUpdatedDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getUpdatedBy())
            {
                ret[pMasqueradingVector[12]]=getValueOfUpdatedBy();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCode())
    {
        ret["code"]=getValueOfCode();
    }
    else
    {
        ret["code"]=Json::Value();
    }
    if(getLineno())
    {
        ret["LineNo"]=getValueOfLineno();
    }
    else
    {
        ret["LineNo"]=Json::Value();
    }
    if(getStartDate())
    {
        ret["start_date"]=getStartDate()->toDbStringLocal();
    }
    else
    {
        ret["start_date"]=Json::Value();
    }
    if(getStartSerialNo())
    {
        ret["start_serial_no"]=getValueOfStartSerialNo();
    }
    else
    {
        ret["start_serial_no"]=Json::Value();
    }
    if(getPrefix())
    {
        ret["prefix"]=getValueOfPrefix();
    }
    else
    {
        ret["prefix"]=Json::Value();
    }
    if(getSuffix())
    {
        ret["suffix"]=getValueOfSuffix();
    }
    else
    {
        ret["suffix"]=Json::Value();
    }
    if(getStep())
    {
        ret["step"]=getValueOfStep();
    }
    else
    {
        ret["step"]=Json::Value();
    }
    if(getLastSerialNo())
    {
        ret["last_serial_no"]=getValueOfLastSerialNo();
    }
    else
    {
        ret["last_serial_no"]=Json::Value();
    }
    if(getLastUsedDate())
    {
        ret["last_used_date"]=getLastUsedDate()->toDbStringLocal();
    }
    else
    {
        ret["last_used_date"]=Json::Value();
    }
    if(getCreatedDate())
    {
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    }
    else
    {
        ret["created_date"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getUpdatedDate())
    {
        ret["updated_date"]=getUpdatedDate()->toDbStringLocal();
    }
    else
    {
        ret["updated_date"]=Json::Value();
    }
    if(getUpdatedBy())
    {
        ret["updated_by"]=getValueOfUpdatedBy();
    }
    else
    {
        ret["updated_by"]=Json::Value();
    }
    return ret;
}

bool SystemSerialDetail::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("code"))
    {
        if(!validJsonOfField(0, "code", pJson["code"], err, true))
            return false;
    }
    if(pJson.isMember("LineNo"))
    {
        if(!validJsonOfField(1, "LineNo", pJson["LineNo"], err, true))
            return false;
    }
    else
    {
        err="The LineNo column cannot be null";
        return false;
    }
    if(pJson.isMember("start_date"))
    {
        if(!validJsonOfField(2, "start_date", pJson["start_date"], err, true))
            return false;
    }
    if(pJson.isMember("start_serial_no"))
    {
        if(!validJsonOfField(3, "start_serial_no", pJson["start_serial_no"], err, true))
            return false;
    }
    if(pJson.isMember("prefix"))
    {
        if(!validJsonOfField(4, "prefix", pJson["prefix"], err, true))
            return false;
    }
    if(pJson.isMember("suffix"))
    {
        if(!validJsonOfField(5, "suffix", pJson["suffix"], err, true))
            return false;
    }
    if(pJson.isMember("step"))
    {
        if(!validJsonOfField(6, "step", pJson["step"], err, true))
            return false;
    }
    if(pJson.isMember("last_serial_no"))
    {
        if(!validJsonOfField(7, "last_serial_no", pJson["last_serial_no"], err, true))
            return false;
    }
    if(pJson.isMember("last_used_date"))
    {
        if(!validJsonOfField(8, "last_used_date", pJson["last_used_date"], err, true))
            return false;
    }
    if(pJson.isMember("created_date"))
    {
        if(!validJsonOfField(9, "created_date", pJson["created_date"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(10, "created_by", pJson["created_by"], err, true))
            return false;
    }
    if(pJson.isMember("updated_date"))
    {
        if(!validJsonOfField(11, "updated_date", pJson["updated_date"], err, true))
            return false;
    }
    if(pJson.isMember("updated_by"))
    {
        if(!validJsonOfField(12, "updated_by", pJson["updated_by"], err, true))
            return false;
    }
    return true;
}
bool SystemSerialDetail::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SystemSerialDetail::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("code"))
    {
        if(!validJsonOfField(0, "code", pJson["code"], err, false))
            return false;
    }
    if(pJson.isMember("LineNo"))
    {
        if(!validJsonOfField(1, "LineNo", pJson["LineNo"], err, false))
            return false;
    }
    if(pJson.isMember("start_date"))
    {
        if(!validJsonOfField(2, "start_date", pJson["start_date"], err, false))
            return false;
    }
    if(pJson.isMember("start_serial_no"))
    {
        if(!validJsonOfField(3, "start_serial_no", pJson["start_serial_no"], err, false))
            return false;
    }
    if(pJson.isMember("prefix"))
    {
        if(!validJsonOfField(4, "prefix", pJson["prefix"], err, false))
            return false;
    }
    if(pJson.isMember("suffix"))
    {
        if(!validJsonOfField(5, "suffix", pJson["suffix"], err, false))
            return false;
    }
    if(pJson.isMember("step"))
    {
        if(!validJsonOfField(6, "step", pJson["step"], err, false))
            return false;
    }
    if(pJson.isMember("last_serial_no"))
    {
        if(!validJsonOfField(7, "last_serial_no", pJson["last_serial_no"], err, false))
            return false;
    }
    if(pJson.isMember("last_used_date"))
    {
        if(!validJsonOfField(8, "last_used_date", pJson["last_used_date"], err, false))
            return false;
    }
    if(pJson.isMember("created_date"))
    {
        if(!validJsonOfField(9, "created_date", pJson["created_date"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(10, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("updated_date"))
    {
        if(!validJsonOfField(11, "updated_date", pJson["updated_date"], err, false))
            return false;
    }
    if(pJson.isMember("updated_by"))
    {
        if(!validJsonOfField(12, "updated_by", pJson["updated_by"], err, false))
            return false;
    }
    return true;
}
bool SystemSerialDetail::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SystemSerialDetail::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }

            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }

            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
