/**
 *
 *  TdRunnumber.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace test
{
class TmProgram;

class TdRunnumber
{
  public:
    struct Cols
    {
        static const std::string _programid;
        static const std::string _Year;
        static const std::string _Month;
        static const std::string _additional;
        static const std::string _runningnumber;
        static const std::string _insertdate;
        static const std::string _updatedate;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = void;
    int getPrimaryKey() const { assert(false); return 0; }

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit TdRunnumber(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit TdRunnumber(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    TdRunnumber(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    TdRunnumber() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column programid  */
    ///Get the value of the column programid, returns the default value if the column is null
    const int32_t &getValueOfProgramid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getProgramid() const noexcept;
    ///Set the value of the column programid
    void setProgramid(const int32_t &pProgramid) noexcept;

    /**  For column Year  */
    ///Get the value of the column Year, returns the default value if the column is null
    const std::string &getValueOfYear() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getYear() const noexcept;
    ///Set the value of the column Year
    void setYear(const std::string &pYear) noexcept;
    void setYear(std::string &&pYear) noexcept;
    void setYearToNull() noexcept;

    /**  For column Month  */
    ///Get the value of the column Month, returns the default value if the column is null
    const std::string &getValueOfMonth() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMonth() const noexcept;
    ///Set the value of the column Month
    void setMonth(const std::string &pMonth) noexcept;
    void setMonth(std::string &&pMonth) noexcept;
    void setMonthToNull() noexcept;

    /**  For column additional  */
    ///Get the value of the column additional, returns the default value if the column is null
    const std::string &getValueOfAdditional() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAdditional() const noexcept;
    ///Set the value of the column additional
    void setAdditional(const std::string &pAdditional) noexcept;
    void setAdditional(std::string &&pAdditional) noexcept;
    void setAdditionalToNull() noexcept;

    /**  For column runningnumber  */
    ///Get the value of the column runningnumber, returns the default value if the column is null
    const int32_t &getValueOfRunningnumber() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRunningnumber() const noexcept;
    ///Set the value of the column runningnumber
    void setRunningnumber(const int32_t &pRunningnumber) noexcept;

    /**  For column insertdate  */
    ///Get the value of the column insertdate, returns the default value if the column is null
    const ::trantor::Date &getValueOfInsertdate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getInsertdate() const noexcept;
    ///Set the value of the column insertdate
    void setInsertdate(const ::trantor::Date &pInsertdate) noexcept;

    /**  For column updatedate  */
    ///Get the value of the column updatedate, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedate() const noexcept;
    ///Set the value of the column updatedate
    void setUpdatedate(const ::trantor::Date &pUpdatedate) noexcept;
    void setUpdatedateToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    TmProgram getTm_program(const drogon::orm::DbClientPtr &clientPtr) const;
    void getTm_program(const drogon::orm::DbClientPtr &clientPtr,
                       const std::function<void(TmProgram)> &rcb,
                       const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<TdRunnumber>;
    friend drogon::orm::BaseBuilder<TdRunnumber, true, true>;
    friend drogon::orm::BaseBuilder<TdRunnumber, true, false>;
    friend drogon::orm::BaseBuilder<TdRunnumber, false, true>;
    friend drogon::orm::BaseBuilder<TdRunnumber, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<TdRunnumber>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> programid_;
    std::shared_ptr<std::string> year_;
    std::shared_ptr<std::string> month_;
    std::shared_ptr<std::string> additional_;
    std::shared_ptr<int32_t> runningnumber_;
    std::shared_ptr<::trantor::Date> insertdate_;
    std::shared_ptr<::trantor::Date> updatedate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "programid,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "Year,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "Month,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "additional,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "runningnumber,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "insertdate,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "updatedate,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace test
} // namespace drogon_model
